### ISSUE TITLE
Channel error and no yml files gets generated

### ISSUE THREAD

**Issue by fogers777** [Suremaker/OctopusProjectBuilder#2]
Hi! Found this project today and wanted to try, but i'm facing some issues. Would appreciate some help:

When trying to download ( C:\GIT\OctopusProjectBuilder.Console.1.0.4.0> .\OctopusProjectBuilder.Console.exe -a download -d C:\temp\configs -u http://url/api -k API-*****************) it shows that it is downloading my projects LibraryVariableSetResource, LifecycleResource, ProjectGroupResource, ProjectResource,and then errors comes up - [ERROR] Application Error: Unsupported ScopeField: Channel

Also i don't see any yml files being generated during this process.  Are they generated once everything is completed?

Cheers!

**Comment by Suremaker** [comment]
Hello,

Sorry for the delayed response, I did not noticed this message until today.
The builder does not support the channels yet, which means that currently it fails with yaml generation.
I will take a look if anything has changed in the Octopus.Client since then and if I can implement the support for it now.

Regarding your other question, yes, the files are created after the full model is retrieved from the Octopus.

**Comment by Suremaker** [comment]
The variables referencing project channel are downloaded and uploaded properly with version 1.5.1 (available in nuget).

#11 has been created to add full support for project channels
